/**
 * 50+ Common IPC (Indian Penal Code) sections for autocomplete
 */
const ipcSections = [
  { code: 'IPC 107', title: 'Abetment of a thing', description: 'Abetment of a crime', category: 'Abetment' },
  { code: 'IPC 108', title: 'Abettor', description: 'A person abets an offence', category: 'Abetment' },
  { code: 'IPC 109', title: 'Punishment of abetment', description: 'Punishment of abetment if act abetted is committed', category: 'Abetment' },
  { code: 'IPC 120B', title: 'Criminal conspiracy', description: 'Punishment of criminal conspiracy', category: 'Criminal Conspiracy' },
  { code: 'IPC 141', title: 'Unlawful assembly', description: 'Assembly of five or more persons constituting unlawful assembly', category: 'Public Order' },
  { code: 'IPC 143', title: 'Punishment for unlawful assembly', description: 'Punishment for being member of unlawful assembly', category: 'Public Order' },
  { code: 'IPC 144', title: 'Joining unlawful assembly', description: 'Joining unlawful assembly armed with deadly weapon', category: 'Public Order' },
  { code: 'IPC 147', title: 'Rioting', description: 'Punishment for rioting', category: 'Public Order' },
  { code: 'IPC 148', title: 'Rioting armed with deadly weapon', description: 'Rioting with deadly weapon', category: 'Public Order' },
  { code: 'IPC 149', title: 'Unlawful assembly - common object', description: 'Every member of unlawful assembly guilty of offence committed in prosecution of common object', category: 'Public Order' },
  { code: 'IPC 153A', title: 'Promoting enmity between groups', description: 'Promoting enmity between different groups on grounds of religion, race, etc.', category: 'Public Order' },
  { code: 'IPC 171', title: 'Wearing garb or carrying token used by public servant', description: 'Public servant related offence', category: 'Public Servant' },
  { code: 'IPC 186', title: 'Obstructing public servant', description: 'Obstructing public servant in discharge of public functions', category: 'Public Servant' },
  { code: 'IPC 191', title: 'Giving false evidence', description: 'Giving false evidence', category: 'False Evidence' },
  { code: 'IPC 193', title: 'Punishment for false evidence', description: 'Punishment for giving false evidence in any proceeding', category: 'False Evidence' },
  { code: 'IPC 195A', title: 'Threatening to give false evidence', description: 'Threatening any person to give false evidence', category: 'False Evidence' },
  { code: 'IPC 268', title: 'Public nuisance', description: 'Public nuisance definition', category: 'Public Health' },
  { code: 'IPC 279', title: 'Rash driving or riding', description: 'Rash driving or riding on public way', category: 'Road Offences' },
  { code: 'IPC 280', title: 'Rash navigation of vessel', description: 'Rash navigation of vessel endangering human life', category: 'Road Offences' },
  { code: 'IPC 294', title: 'Obscene acts and songs', description: 'Obscene acts or songs in any public place', category: 'Obscenity' },
  { code: 'IPC 295A', title: 'Deliberate acts to outrage religious feelings', description: 'Deliberate and malicious acts intended to outrage religious feelings', category: 'Religion' },
  { code: 'IPC 302', title: 'Punishment for murder', description: 'Whoever commits murder shall be punished with death or imprisonment for life', category: 'Homicide' },
  { code: 'IPC 304', title: 'Culpable homicide not amounting to murder', description: 'Punishment for culpable homicide not amounting to murder', category: 'Homicide' },
  { code: 'IPC 304A', title: 'Causing death by negligence', description: 'Causing death by doing any rash or negligent act', category: 'Homicide' },
  { code: 'IPC 304B', title: 'Dowry death', description: 'Death of woman within 7 years of marriage under abnormal circumstances', category: 'Dowry' },
  { code: 'IPC 306', title: 'Abetment of suicide', description: 'If any person commits suicide, whoever abets the commission', category: 'Suicide' },
  { code: 'IPC 307', title: 'Attempt to murder', description: 'Whoever attempts to commit murder', category: 'Homicide' },
  { code: 'IPC 308', title: 'Attempt to commit culpable homicide', description: 'Attempt to commit culpable homicide', category: 'Homicide' },
  { code: 'IPC 323', title: 'Voluntarily causing hurt', description: 'Punishment for voluntarily causing hurt', category: 'Assault' },
  { code: 'IPC 324', title: 'Hurt by dangerous weapons', description: 'Voluntarily causing hurt by dangerous weapons or means', category: 'Assault' },
  { code: 'IPC 325', title: 'Grievous hurt', description: 'Punishment for voluntarily causing grievous hurt', category: 'Assault' },
  { code: 'IPC 326', title: 'Grievous hurt by dangerous weapons', description: 'Voluntarily causing grievous hurt by dangerous weapons or means', category: 'Assault' },
  { code: 'IPC 341', title: 'Wrongful restraint', description: 'Punishment for wrongful restraint', category: 'Restraint' },
  { code: 'IPC 342', title: 'Wrongful confinement', description: 'Punishment for wrongful confinement', category: 'Restraint' },
  { code: 'IPC 354', title: 'Assault on woman with intent to outrage modesty', description: 'Assault or criminal force on woman with intent to outrage her modesty', category: 'Women Safety' },
  { code: 'IPC 354A', title: 'Sexual harassment', description: 'Sexual harassment and punishment for sexual harassment', category: 'Women Safety' },
  { code: 'IPC 354D', title: 'Stalking', description: 'Stalking of a woman', category: 'Women Safety' },
  { code: 'IPC 363', title: 'Kidnapping', description: 'Punishment for kidnapping from lawful guardianship', category: 'Kidnapping' },
  { code: 'IPC 365', title: 'Kidnapping for ransom', description: 'Kidnapping or abducting with intent to secretly and wrongfully confine person', category: 'Kidnapping' },
  { code: 'IPC 376', title: 'Rape', description: 'Punishment for rape', category: 'Sexual Offences' },
  { code: 'IPC 379', title: 'Theft', description: 'Punishment for theft', category: 'Property Offences' },
  { code: 'IPC 380', title: 'Theft in dwelling house', description: 'Theft in dwelling house, etc.', category: 'Property Offences' },
  { code: 'IPC 384', title: 'Extortion', description: 'Punishment for extortion', category: 'Property Offences' },
  { code: 'IPC 392', title: 'Robbery', description: 'Punishment for robbery', category: 'Property Offences' },
  { code: 'IPC 395', title: 'Dacoity', description: 'Punishment for dacoity', category: 'Property Offences' },
  { code: 'IPC 406', title: 'Criminal breach of trust', description: 'Punishment for criminal breach of trust', category: 'Fraud' },
  { code: 'IPC 415', title: 'Cheating', description: 'Definition of cheating', category: 'Fraud' },
  { code: 'IPC 417', title: 'Punishment for cheating', description: 'Punishment for cheating', category: 'Fraud' },
  { code: 'IPC 420', title: 'Cheating and dishonestly inducing delivery of property', description: 'Cheating and dishonestly inducing delivery of property', category: 'Fraud' },
  { code: 'IPC 426', title: 'Mischief', description: 'Punishment for mischief', category: 'Mischief' },
  { code: 'IPC 427', title: 'Mischief causing damage', description: 'Mischief causing damage to the amount of fifty rupees', category: 'Mischief' },
  { code: 'IPC 435', title: 'Mischief by fire', description: 'Mischief by fire or explosive substance', category: 'Mischief' },
  { code: 'IPC 447', title: 'Criminal trespass', description: 'Punishment for criminal trespass', category: 'Trespass' },
  { code: 'IPC 448', title: 'House trespass', description: 'Punishment for house-trespass', category: 'Trespass' },
  { code: 'IPC 452', title: 'House-trespass to commit offence', description: 'House-trespass after preparation for hurt, assault or wrongful restraint', category: 'Trespass' },
  { code: 'IPC 457', title: 'Lurking house-trespass by night', description: 'Lurking house-trespass or house-breaking by night', category: 'Trespass' },
  { code: 'IPC 468', title: 'Forgery for purpose of cheating', description: 'Forgery for purpose of cheating', category: 'Forgery' },
  { code: 'IPC 471', title: 'Using forged document', description: 'Using as genuine a forged document or electronic record', category: 'Forgery' },
  { code: 'IPC 494', title: 'Bigamy', description: 'Marrying again during lifetime of husband or wife', category: 'Marriage' },
  { code: 'IPC 498A', title: 'Cruelty by husband or relatives', description: 'Husband or relative of husband of a woman subjecting her to cruelty', category: 'Dowry' },
  { code: 'IPC 500', title: 'Defamation', description: 'Punishment for defamation', category: 'Defamation' },
  { code: 'IPC 504', title: 'Intentional insult to provoke breach of peace', description: 'Intentional insult with intent to provoke breach of the peace', category: 'Public Order' },
  { code: 'IPC 506', title: 'Criminal intimidation', description: 'Punishment for criminal intimidation', category: 'Intimidation' },
  { code: 'IPC 509', title: 'Word, gesture to insult modesty of woman', description: 'Word, gesture or act intended to insult the modesty of a woman', category: 'Women Safety' },
  { code: 'IPC 511', title: 'Attempt to commit offences', description: 'Punishment for attempting to commit offences punishable with imprisonment for life', category: 'General' },
];

module.exports = ipcSections;
